haproxy-0:
  image: myha
  links:
   - server1
   - server2
   - server3
  ports:
   - "8888:80"
  volumes: 
    - ./haproxy/keepalived1/:/etc/keepalived
haproxy-1:
  image: myha
  links:
   - server1
   - server2
   - server3
  ports:
   - "9999:80"
  volumes: 
    - ./haproxy/keepalived2/:/etc/keepalived

server1:
  image: myn
server2:
  image: myn
  volumes: 
    - ./nginx/server2/:/usr/share/nginx/html/
server3:
  image: myn
  volumes: 
    - ./nginx/server3/:/usr/share/nginx/html/