# To run on localhost change the servers in the haproxy.cfg
# and uncomment the non-arm64 base images in the nginx
# and haproxy dockerfiles
haproxy:
  build: ./haproxy
  links:
   - server1
   - server2
   - server3
  ports:
   - "80:80"

server1:
  build: ./nginx
  volumes: 
    - ./nginx/server1/:/usr/share/nginx/html/

server2:
  build: ./nginx
  volumes: 
    - ./nginx/server2/:/usr/share/nginx/html/

server3:
  build: ./nginx
  volumes: 
    - ./nginx/server3/:/usr/share/nginx/html/