haproxy:
  image: myha
  links:
   - server1
   - server2
   - server3
  ports:
   - "80:80"

server1:
  image: myn
server2:
  image: myn
  volumes: 
    - ./nginx/server2/:/usr/share/nginx/html/
server3:
  image: myn
  volumes: 
    - ./nginx/server3/:/usr/share/nginx/html/