---

-
  name: "Ubuntu update & upgrade"
  shell: "apt-get -y install && apt-get -y update"
  become: true

-
  name: "Install docker"
  shell: "sudo apt-get install docker.io"
  become: true
  register: output
  
- 
  debug: var=output