---

-
  name: "Build haproxy image"
  docker_image: 
     path: ./haproxy
     name: haproxy
     state: present

-
  name: "Run haproxy container"
    docker:
      name: haproxy_instance
      image: "haproxy"
      state: started
      restart: yes
      publish_all_ports: yes
    