---

-
  name: "Make haproxy dir"
  shell: "mkdir -p /home/ubuntu/haproxy"

-
  name: "Copy docker files"
  synchronize:
    src: ../haproxy
    dest: /home/ubuntu/
 
-
  name: "Build haproxy image"
  shell: "cd haproxy && docker build -t haproxy ."
  become: true

-
  name: "Run container"
  hell: "docker run -d --name haproxy_instance -p 80:80 --restart=always haproxy"
  become: true
