---

# Playbook to build and run docker containers

- name: "Build and run haproxy docker image"
  hosts: balancers
  remote_user: ubuntu
  roles:
    - {role: docker}

- name: "Build and run nginx docker image"
  hosts: servers
  remote_user: ubuntu
  roles:
    - {role: docker}
