---

-
  name: "Install Keepalived"
  shell: "apt-get install -y keepalived"
  become: true

-
  name: "Install psmisc toolkit"
  shell: "apt-get install psmisc"
  become: true

-
  name: "Copy configuration files"
  synchronize:
    src: ../keepalived
    dest: /home/ubuntu/
